name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install dependencies
      run: npm ci

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_PATH: ${{ secrets.EC2_PATH }}
      run: |
        # Write the SSH private key to a file
        echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > private_key.pem
        chmod 600 private_key.pem

        # Use the private key to SSH into the server
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "pm2 stop all"
        rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./* $EC2_USER@$EC2_HOST:$EC2_PATH
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "cd $EC2_PATH && npm install && pm2 restart ecosystem.config.js"
        # ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "pm2 restart ecosystem.config.js"
      shell: bash
